# run: conda env create --file environment.yml
name: docker_env_v5
dependencies:
- python
- pip
- numpy
- pytorch
- joblib
- scikit-learn
- tqdm
- scipy
- matplotlib
- tensorboard
- pip:
  - minerl
  - pfrl
  - wandb
